### ISSUE TITLE
Genome2OR installed centrally causes OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by jehalter0** [ToHanwei/Genome2OR#5]
This same command works if I create a personal mamba environment, but when trying it in a centrally install mamba environment where the application dir is read-only to users, the command fails due to the error "OSError: [Errno 30] Read-only file system: '/apps/pkg/mambaforge/4.14/envs/genome2or-1.1.0/bin/hmmbuild'"

$ genome2or Actinopteri outputdir genome.fasta -e 1e-10 -c 16 -p prefix

    ____ _____ _   _  ___  __  __ _____ ____   ___  ____
   / ___| ____| \ | |/ _ \|  \/  | ____|___ \ / _ \|  _ \
  | |  _|  _| |  \| | | | | |\/| |  _|   __) | | | | |_) |
  | |_| | |___| |\  | |_| | |  | | |___ / __/| |_| |  _ <
   \____|_____|_| \_|\___/|_|  |_|_____|_____|\___/|_| \_|

2024-02-22 13:22:06,358 Functions.py:INFO ###genome2or program starts running###
Traceback (most recent call last):
  File "genome2or.py", line 155, in <module>
  File "genome2or.py", line 123, in main
  File "src/Functions.py", line 1830, in chmod
OSError: [Errno 30] Read-only file system: '/apps/pkg/mambaforge/4.14/envs/genome2or-1.1.0/bin/hmmbuild'
[396575] Failed to execute script 'genome2or' due to unhandled exception!

**Comment by ToHanwei** [comment]
It seems that the issue you are encountering may be related to installation. You could try to manually reinstall the HMMER tool. Additionally, the problem could also be related to the file permissions on your computer system. We recommend creating a new conda environment for the installation, which might avoid a lot of unnecessary trouble.
